### ISSUE TITLE
ALG: Flipping wheel doesn't flip base model

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/KSPWheel#11]
Causing door to clip into the strut when changing the angle

![screenshot0](https://cloud.githubusercontent.com/assets/10545461/22363014/06990cd4-e41c-11e6-966d-affa83ab59e3.png)

**Comment by shadowmage45** [comment]
Yeah, you need to hit the 'fleep wheel' button after they have been placed in symmetry.  This causes both parts to re-check their symmetry state and update appropriately.  Sadly it only works when both parts are present (as the cloned part always serializes from the original part, and so starts in the same state).

I have no idea how to detect if a part is placed in symmetry and to act on its initial state in a proper and robust manner.  All of the checks I can think of fail in specific cases and would cause improper operation at some point.  Specifically checking if part.isClone is inconsistent; it works the first time, but it is not persistent so cannot be relied upon.  Trying to check the part.symmetryCounterparts list during OnStart often returns modules that have not been fully initialized, if they are even present (depends on order-of-loading between the parts), and outright fails on the initial part (when first pulled from parts-list, prior to being placed, there is no symmetry yet).

I tried using a persistent boolean that was set when the part was first placed -- examine symmetry, do appropriate actions, flip the bool value to indicate that symmetry has been handled.  However this fails in the editor when a user alt-click clones a part or places things in symmetry, as it will serialize that bool across to the cloned parts, which then think they are already initialized / have already handled their symmetry updates.  Basically, this comes back to my long standing dislike of stock part-initialization code.  Namely there is not a single consistent order of operations that occur when loading a part that can be relied upon.
  
---
  
Are you aware of any fool-proof methods for detecting part symmetry status during the OnStart of each individual part, **without querying or touching any other parts or modules** (which may or may not be present or in a valid state during the OnStart of the first part)?

Or at what point is it guaranteed to always be safe to examine symmetry counterparts, and how can you know which is the original part and which is the clone?  (the part.isClone flag gets cleared on craft reload as near as I can tell, so can only be used when the parts are initially placed)

Or how can I have a boolean 'has checked symmetry' value that is both persistent for a part and not serialized into clones in the editor?  As soon as I make it public/persistent, it gets cloned to copied parts and entirely defeats the purpose of the flag.

**Comment by KerbalFoundries** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/81664-plugin-wip-mirror-symmetry-for-asymmetrical-parts/

**Comment by shadowmage45** [comment]
Thanks, I'll certainly have to take a look at that.  

If I'm reading it right it handles it by leaving the 'first' part in an uninitialized state (as no clone is found when the part is first pulled out of the editor part list), and the symmetry updating only happens once the symmetry part is placed (which then finds the 'original' part in its findclone() method).  Hmm....

On a related note to that link -- I still haven't found a good way to handle 'sided' / asymmetrical parts yet (without compiling distinct models for each side/including both sides in a single model).  It is on my long list of TODO, but I first need to find a way to re-initialize all of the modules cleanly when the models/sides are changed (as they will need to update their cached transforms/etc) (unless I disallow the user to set the side and handle it all explicitly in code, in which case I can setup the model before the rest of the modules are initialized, but there would be no opportunity to change it once it was initially setup; if the initial sides chosen were wrong the users only recourse would be to physically move the part to the other side).

@KerbalFoundries 
And since I've got your attention here for a moment -- is there a repository or other source for the KerbalFoundries modeling assets?  
I would love to adjust a few of the models to modernize them (remove bounds colliders mostly), but the tracks in particular do not import well through the blender .mu importer tool (the skinned meshes end up all sorts of wrong, and I'm not familiar enough with skinned meshes to fix them properly without a lengthy learning process first).

**Comment by KerbalFoundries** [comment]
It's the product of hours of banging my head against KSP, and I honestly
can't remember what I did. All I know is it still (by some miracle) works
in the latest versions.

I experimented with simply setting Game objects to scale -1 on the X axis,
but this causes a world of pain with colliders, normals and all sorts. A
mesh re-bake (see xEvilReeperx's part preview size fixer plug in, which I
think got baked into KF for details) shifting x axis positions of some
verts would probably have the required result.

No, there isn't. I saw the crazy shenanigans that happened with the RBI
stuff, and decided it was best not to. My stuff is not rigged in anywhere
near standard ways! I'm happy to hand it over to your good self, though.
I'll just do a zip of the 3d Studio source files, plus the unity assets if
 that's OK?

**Comment by shadowmage45** [comment]
Indeed, I am all too familiar with banging my head against KSP and Unity.  Probably a few dents left in one or the other...

I think I understand what is going on from the part-cloning code a bit better, or at least I have an idea for a potential solution from the code you linked.  Should let me fix up the current problems with the left/right handed parts at least.

Yea, I've noticed major problems with simple negative scaling on stuff.  My thoughts were, for a more complete method, to go in and manually invert the verts in the meshes.  But there is still the problem of transform orientations that I haven't been able to find a solution for (can't simply rotate them, nor can they be inverted through scaling)....  Seems like having separate models for left/right is the only workable way to do it.

Understood on the models and assets -- is the same reason I keep all of my SSTU model assets in a private repository.  Yes, a zipped up package would be great if available;  feel free to PM to me through KSP forums, or I can provide a direct email address if needed.  And thanks, is much appreciated :)

**Comment by shadowmage45** [comment]
Fixed in dev code (using a system loosely based on that linked by LoFi earlier).  Doing some further validation and testing now, but seems like it will work appropriately.  Will be available with the next release if no problems are found.

Thanks for the hints @KerbalFoundries , I probably would have banged my head on that one for a awhile before I found a solution.

**Comment by KerbalFoundries** [comment]
Glad I could help! I keep a loose eye on the updates, and knowing I had
this one nailed and it still works, I couldn't let you go through all that
needlessly.

Keep up the great work :)
