### ISSUE TITLE
Steering inverted, Forward Drive leads to spin on Default Settings.

### ISSUE THREAD

**Issue by Madrias** [shadowmage45/KSPWheel#3]
Fairly simple issue from my testing.  Steering (both wheels and tank style) is inverted by default from the actual intended command (steering right actually steers you left, and the opposite applies).  This is reasonably easily fixed on the end-user side by manually inverting all intended steering wheels, but it is an issue.

However, the other half of the issue is that when pairing two parts together using symmetry (I did not test individual attachment, however, so I can't be sure that the issue exists there), all wheels on the right side will drive backwards.  Again, easily fixed on the end-user side by inverting the motor drive for all intended drive wheels, but it can be an unexpected surprise to attempt to accelerate and find yourself spinning instead.

Attached are screenshots of the steering issue (Steering full right gets full left steering lock, and steering full left gets full right steering lock) as well as my KSP.log file.  Sadly, I was not able to capture an image of the spin issue, but it is easily replicated.

To replicate either of these issues, attach the Medium Wheels to a structural I-beam with any cockpit and sufficient power, and use the default settings.  The steering should start out inverted even though the button claims it to be normal, and attempting to drive forward should result in a spin until the right-side drive wheels have their motors inverted.

Screenshots:
![20161128142810_1](https://cloud.githubusercontent.com/assets/8366487/20685798/863f3244-b57b-11e6-8f77-20686370cc84.jpg)
![20161128142821_1](https://cloud.githubusercontent.com/assets/8366487/20685797/863d6d42-b57b-11e6-8aa9-bf0a93ae7f6c.jpg)

KSP.log: (Saved as .txt to upload)  (Note, I turned on Verbose Logging in the KSP options.  If, in the future, you have a preference, please let me know.)
[KSPlog.txt](https://github.com/shadowmage45/KSPWheel/files/617455/KSPlog.txt)

**Comment by shadowmage45** [comment]
Thanks for the report, and especially for including logs and pics; makes it a ton easier to see what you are referring to and make sure there are no simple bugs at fault.


The function of the motor and steering is intended; it is impossible to predict all potential vessel designs, so I left it up to the user to configure the invert settings as desired. The rotation direction of the wheel is set by the model and configs;  all that applying them in symmetry does is rotate the model around, so I would expect motor direction to be inverted.  The goal of these modules is not really to auto-configure everything, but more to open up the options for the engineer to configure.  This is why the Load Rating, Steering Bias, Ride Height, and many of the other toggles exist.  It also gives the benefit of being independent of control-point/control transform location/orientation.  Set them up once and they will always respond the same.

However, for ease of use, I will investigate adding an automatic-invert to motor direction whenever using mirror symmetry in the editor.  This would keep the mirror counterpart set to the opposite, which should be applicable for most designs using mirror symmetry.  Would be un-linked in flight scene so motors could still be inverted individually.

Steering is a bit more complicated as determining which direction is 'right' depends on the control transform location and orientation, which I'm not sure is available in the editor.  Might be able to delay it until the start of flight scene (where Vessel is available), but it would then end up overriding any user setup from the editor.  

I suppose an easy quality-of-life improvement for steering is to invert the default rotation direction so that wheels at the front of a craft are at least turning the  proper way by default (but wheels at the rear would be turning opposite by default).

**Comment by Madrias** [comment]
Understandable.  The ease of use automatic-invert on mirror symmetry would be most welcome.  Also to default-invert the steering orientation, as any vessel using rear-wheel-steering is going to likely have fewer wheels steering.  If you could share steering invert/normal across Symmetry, that'd make configuration of large vessels easier, but isn't exactly necessary, just another ease-of-use / quality-of-life improvement.

I understand as well about including logs and screenshots.  Chasing glitches is always a pain in the butt.  (Currently chasing a bug that likes to make my desktop crash on first boot, but subsequent warm restarts are just fine.  Proving rather annoying, but I'll figure it out.  I'm leaning toward bad memory.)

**Comment by shadowmage45** [comment]
Was a problem with the PartModules, which are no longer supported.
